name: appwlogger
description: A simple Dart package for logging appwrite message
version: 0.0.1
repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  dart_appwrite: ^7.2.0
